# permissions for end users to view ovhnginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovhnginx-viewer-role
rules:
- apiGroups:
  - tutorials.ovhcloud.com
  resources:
  - ovhnginxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tutorials.ovhcloud.com
  resources:
  - ovhnginxes/status
  verbs:
  - get
